// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.API.Data;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119110307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create normalized database schema for scalable task management",
                            IsComplete = false,
                            Title = "Design PostgreSQL schema with users, projects, and tasks tables"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add token-based authentication with refresh token rotation",
                            IsComplete = false,
                            Title = "Implement JWT authentication in ASP.NET Core API"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create multi-stage Dockerfile and configure ACR integration",
                            IsComplete = false,
                            Title = "Build Docker image and push to Azure Container Registry"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add FluentValidation and input sanitization to prevent errors",
                            IsComplete = false,
                            Title = "[URGENT] Fix: POST /api/tasks returns 500 on invalid input - add validation"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Achieve 85%+ code coverage with xUnit and Moq",
                            IsComplete = true,
                            Title = "Write unit tests for TasksController CRUD endpoints"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set up ConfigMaps, secrets, and Helm charts for AKS deployment",
                            IsComplete = true,
                            Title = "Configure staging environment variables and deploy to AKS cluster"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
