// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.API.Data;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111074107_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 53L);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 10, 27, 7, 41, 7, 116, DateTimeKind.Utc).AddTicks(9859),
                            Description = "Create normalized database schema for scalable task management",
                            IsComplete = false,
                            Title = "Design PostgreSQL schema with users, projects, and tasks tables"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 10, 30, 7, 41, 7, 117, DateTimeKind.Utc).AddTicks(146),
                            Description = "Add token-based authentication with refresh token rotation",
                            IsComplete = false,
                            Title = "Implement JWT authentication in ASP.NET Core API"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 11, 3, 7, 41, 7, 117, DateTimeKind.Utc).AddTicks(151),
                            Description = "Create multi-stage Dockerfile and configure ACR integration",
                            IsComplete = false,
                            Title = "Build Docker image and push to Azure Container Registry"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 11, 8, 7, 41, 7, 117, DateTimeKind.Utc).AddTicks(153),
                            Description = "Add FluentValidation and input sanitization to prevent errors",
                            IsComplete = false,
                            Title = "[URGENT] Fix: POST /api/tasks returns 500 on invalid input - add validation"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 41, 7, 117, DateTimeKind.Utc).AddTicks(154),
                            Description = "Achieve 85%+ code coverage with xUnit and Moq",
                            IsComplete = true,
                            Title = "Write unit tests for TasksController CRUD endpoints"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 11, 6, 7, 41, 7, 117, DateTimeKind.Utc).AddTicks(156),
                            Description = "Set up ConfigMaps, secrets, and Helm charts for AKS deployment",
                            IsComplete = true,
                            Title = "Configure staging environment variables and deploy to AKS cluster"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
